services:
  db:
    image: postgres:16
    container_name: atatek_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - atatek_network

  backend:
    image: ghcr.io/karl4th/atatek-backend:latest
    container_name: atatek_backend
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - atatek_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - atatek_network

  nginx:
    image: nginx:stable
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./uploads:/app/public/uploads
    networks:
      - atatek_network
    restart: unless-stopped

  frontend:
    image: ghcr.io/karl4th/atatek-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: atatek-frontend
    restart: unless-stopped
    networks:
      - atatek_network
    volumes:
      - ./uploads:/app/public/uploads

networks:
  atatek_network:
    driver: bridge

volumes:
  postgres_data:
