name: Frontend Rebuild

on:
  repository_dispatch:
    types: [frontend-build-complete]

jobs:
  rebuild-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild frontend containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.PATH }}
            sudo docker compose pull frontend
            sudo docker compose up -d frontend
            sudo docker image prune -f 
            